pipeline {
    agent any
    tools {
        nodejs 'NodeJS 18.16.1'
    }
    environment {
        CONTAINER_NAME = "my_vue"
        IMAGE_NAME = "vue_app"
        VUE_APP_PATH = "Frontend/front_cli"
        VUE_PORT = "3030"
    }

    stages {
        stage('nodejs 18') {
            steps {
                echo "nodejs ============================="
                sh 'node --version'
            }
        }
        stage('Git Clone') {
            steps {
                git branch: 'Front', credentialsId: 'jenkins_token',
                    url: 'https://lab.ssafy.com/s09-webmobile1-sub2/S09P12B202.git'
            }
            post {
                success {
                    echo "Successfully Cloned Repository"
                }
                failure {
                    echo "Fail Cloned Repository"
                }
            }
        }

        stage('Print current File'){
            steps{
                sh 'ls -R'
            }
            post {
                success {
                    echo "Print current File Succeeded"
                }
                failure {
                    echo "Print current File Failed"
                }
            }
        }

        stage('Build and Test') {
            steps {
                dir(VUE_APP_PATH) {
                    sh 'npm install'
                    sh 'npm run build'
                }
            }
            post {
                success {
                    echo "Build and Test Succeeded"
                }
                failure {
                    echo "Build and Test Failed"
                }
            }
        }

        stage('Docker Delete') {
            steps {
                script {
                    try{
                        sh 'echo "Docker Delete Start"'
                        // 컨테이너 존재 시 삭제
                        sh "docker stop ${CONTAINER_NAME}"
                        sh "docker rm -f ${CONTAINER_NAME}"
                    }catch (Exception e){
                        echo "Docker container ${CONTAINER_NAME} does not exist. skip"
                    }
                    try{
                        // 이미지 존재 시 삭제
                        sh "docker image rm ${IMAGE_NAME}"
                    }catch (Exception e){
                        echo "Docker image ${IMAGE_NAME} does not exist. skip"
                    }
                }
            }
            post {
                success {
                    sh 'echo "Docker delete Success"'
                }
                failure {
                    sh 'echo "Docker delete Fail"'
                }
            }
        }

        stage('Docker Build') {
            steps {
                sh 'echo "Building Docker Image"'
                sh 'docker build -t ${IMAGE_NAME} ${VUE_APP_PATH}'
            }
            post {
                success {
                    echo "Docker Image Build Succeeded"
                }
                failure {
                    echo "Docker Image Build Failed"
                }
            }
        }

        stage('Docker Run') {
            steps {
                sh 'echo "Running Docker Container"'
                sh "docker run -d --name ${CONTAINER_NAME} -p ${VUE_PORT}:80 ${IMAGE_NAME}"
            }
            post {
                success {
                    echo "Docker Container Started"
                }
                failure {
                    echo "Failed to Start Docker Container"
                }
            }
        }

        stage('Deploy') {
            steps {
                sh 'echo "Deploying to Remote Server"'
                // 원격 서버로 이미지 전송 및 컨테이너 실행 등의 작업을 추가 (서버에 Docker가 필요)
                // 이 단계는 프로젝트의 구체적인 배포 요구 사항에 따라 다양하게 수정될 수 있습니다.
                // 원격 배포 스크립트, 인증 정보, 서버 환경 구성 등을 포함해야 합니다.
            }
            post {
                success {
                    echo 'Deploy Success'
                }
                failure {
                    echo 'Deploy Failed'
                }
            }
        }
    }
}
