pipeline {
    agent any
    stages {
        stage('Clone') {
            steps {
                git branch: 'Back', credentialsId: 'jenkins_token',
                    url: 'https://lab.ssafy.com/s09-webmobile1-sub2/S09P12B202.git'
            }
            post {
                success {
                    sh 'echo "Successfully Cloned Repository"'
                }
                failure {
                    sh 'echo "Fail Cloned Repository"'
                }
            }
        }

        stage('Build') {
            steps {
                dir('Backend/NangPaDaePa') {
                    sh 'chmod +x gradlew'
                    sh './gradlew clean build'
                    // 디버깅
                    sh 'ls -al ./build'
                    sh './gradlew build --stacktrace'
                }
            }
            post {
                success {
                    echo 'gradle build success'
                }

                failure {
                    echo 'gradle build failed'
                }
            }
        }
        stage('Test') {
            steps {
                echo  '테스트 단계와 관련된 몇 가지 단계를 수행합니다.'
            }
        }
        stage('Docker Rm') {
            steps {
                sh 'echo "Docker Rm Start"'
                sh """
                sudo docker stop jenkins
                sudo docker rm jenkins
                sudo docker rmi -f jenkins
                """
            }

            post {
                success {
                    sh 'echo "Docker Rm Success"'
                }
                failure {
                    sh 'echo "Docker Rm Fail"'
                }
            }
        }

        stage('Dockerizing'){
            steps{
                sh 'echo " Image Bulid Start"'
                sh 'sudo docker-compose up -d --build'
            }
            post {
                success {
                    sh 'echo "Bulid Docker Image Success"'
                }

                failure {
                    sh 'echo "Bulid Docker Image Fail"'
                }
            }
        }

        stage('Deploy') {
            steps {
                sh 'sudo docker run --name jenkins -d -p 9090:8080 jenkins'
            }

            post {
                success {
                    echo 'Deploy success'
                }

                failure {
                    echo 'Deploy failed'
                }
            }
        }
    }
}
