spring:
  security:
    oauth2:
      default:
          password: sns_user
      client:
        registration:
          kakao:
            client-id: ad3555fb105357956fe43e6541f0cd84
            redirect-uri: http://127.0.0.1:8080/api/oauth/kakao
            client-authentication-method: POST
            client-secret: UJBGr0md8gtBzYDoe4CxjeeQi65pJE1G
            authorization-grant-type: authorization_code
            client-name: kakao
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id