# Generated by Django 4.2.4 on 2023-08-14 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('ingredient_id', models.IntegerField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=255)),
                ('kor', models.CharField(max_length=255)),
                ('eng', models.CharField(max_length=255)),
                ('level', models.IntegerField()),
                ('upper_class', models.CharField(max_length=255)),
                ('super_upper_class', models.CharField(max_length=255)),
                ('etc', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'ingredient',
                'managed': False,
            },
        ),
    ]
